create table tb_category
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255)
);

create table tb_product
(
    id          bigint generated by default as identity
        primary key,
    description varchar(255),
    img_url     varchar(255),
    name        varchar(255),
    price       double precision
);

create table tb_product_category
(
    product_id  bigint not null
        constraint fkgbof0jclmaf8wn2alsoexxq3u
            references tb_product,
    category_id bigint not null
        constraint fk5r4sbavb4nkd9xpl0f095qs2a
            references tb_category,
    primary key (product_id, category_id)
);

create table tb_user
(
    id       bigint generated by default as identity
        primary key,
    email    varchar(255),
    name     varchar(255),
    password varchar(255),
    phone    varchar(255)
);

create table tb_order
(
    id           bigint generated by default as identity
        primary key,
    moment       timestamp,
    order_status integer,
    client_id    bigint
        constraint fki0x0rv7d65vsceuy33km9567n
            references tb_user
);

create table tb_order_item
(
    price      double precision,
    quantity   integer,
    product_id bigint not null
        constraint fk4h5xid5qehset7qwe5l9c997x
            references tb_product,
    order_id   bigint not null
        constraint fkgeobgl2xu916he8vhljktwxnx
            references tb_order,
    primary key (order_id, product_id)
);

create table tb_payment
(
    moment   timestamp,
    order_id bigint not null
        primary key
        constraint fkokaf4il2cwit4h780c25dv04r
            references tb_order
);


